### ISSUE TITLE
Provide documentation for running the evasion algorithm with VirusTotal

### ISSUE THREAD

**Issue by hakonharnes** [Jacarte/wasm_evasion#2]
Currently, the README file for the project provides documentation for running the evasion algorithm with MINOS using the command:

```
RUST_BACKTRACE=1 RUST_LOG=evasor=debug ./target/release/evasor --dbconn "datas/minos" mutate --seed 0 -s 10 -e --attempts 1000 -p 1 --input <input.wasm> --oracle python3 ../../oracles/minos/minio.py
```

However, it would be beneficial to also provide documentation for running the evasion algorithm with VirusTotal. This should be added to the project's README.

**Comment by Jacarte** [comment]
Added in the main README
